Add flake
holly-hacker/td pull request #2
Opened 2024-01-27 12:08 UTC by TornaxO7

Makes it friendler for `nix` users :)

2024-01-27 16:41 UTC, holly-hacker commented
Hi, thanks for the PR! I haven't used flakes that much myself, so I left some questions and review comments.

I'd like to mention that while `td` will have automatic database upgrading if I get back into developing it, I didn't intend on people following the `main` branch so if I pick up development again, I may move it to a `develop` branch as to not introduce breaking changes to `main`.

2024-02-08 17:53 UTC, holly-hacker requested changes

2024-02-08 17:53 UTC, holly-hacker commented on result
> +/nix/store/lqr5abphj4mdy5wc2n5ipwprvv834mcb-td
I don't think this should be committed

2024-02-08 17:53 UTC, holly-hacker commented on flake.nix
> +          description = " A WIP graph-based TUI TODO app. ";
These additional spaces aren't needed

2024-02-08 17:53 UTC, holly-hacker commented on flake.nix
> +        version = "0.1.0";
Is there a way to mark this version as being a development version? I don't know to what degree this version number matters, but it'd be nice if this indicated that it's a development version. I plan on releasing a v0.1 if I start working on this project again at some point, so it'd be nice to make that distinction then.

2024-02-08 17:53 UTC, holly-hacker commented on flake.nix
> +      systems = [ "x86_64-linux" "aarch64-linux" ];
`td` runs on other platforms too, and I *think* nix works on platforms like MacOS. Is there a reason why that isn't included here?

2024-02-08 17:53 UTC, holly-hacker commented on .github/workflows/update-nix-flake.yaml
> +name: update-flake-lock
I won't be checking this repo weekly to update the flake lockfile, especially since I'm not actively working on `td` right now. I think it's best to remove this workflow and update the flake lockfile manually when development happens.

2024-02-08 17:53 UTC, holly-hacker commented
@TornaxO7 I just noticed that GitHub never saved my feedback, they should be there now. Could you process this feedback?

2024-02-08 17:54 UTC, TornaxO7 commented on result
> +/nix/store/lqr5abphj4mdy5wc2n5ipwprvv834mcb-td
eh yes, you're right

2024-02-08 17:56 UTC, TornaxO7 commented on flake.nix
> +        version = "0.1.0";
I can add a prefix `dev` for the time being.

2024-02-08 17:56 UTC, TornaxO7 commented on flake.nix
> +      systems = [ "x86_64-linux" "aarch64-linux" ];
> Is there a reason why that isn't included here?

nope, I just added some systems which I know :D

2024-02-08 17:57 UTC, TornaxO7 commented
Changes applied

2024-02-08 17:58 UTC, TornaxO7 commented on flake.nix
> +          description = " A WIP graph-based TUI TODO app. ";
removed

2024-02-08 18:25 UTC, holly-hacker commented
Looks good, thanks a lot!

2024-02-08 18:25 UTC, merged

2024-02-08 21:48 UTC, TornaxO7 commented
> Looks good, thanks a lot!

No problem :)